### PR TITLE
Implement CALL

### PR DESCRIPTION
**Pull request by nilsding**

### CODE REVIEW

**Review by coderobe — CHANGES_REQUESTED** [review]
This does not make sense

**Comment by nilsding** [comment]
Tanke

**Review by coderobe — APPROVED** [review]

**Review by coderobe — APPROVED** [review]
This makes sense

**Review by coderobe — APPROVED** [review]
This makes more sense

**Comment by nilsding** [comment]
https://www.youtube.com/watch?v=U2JFDaHH3mg

**Pull request merged**
